version: 1.0.{build}
environment:
  OCTOKIT_OAUTHTOKEN:
    secure: GTM2XFtnpFPq+Vp1eX4iCQMxWOOGL2ut9/zTEn5N91VnygVqdLJNm5n5u23rEWOo
image: Visual Studio 2017
configuration: Release
platform: Any CPU
install:
- cmd: appveyor downloadfile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
before_build:
- ps: nuget restore
build:
  verbosity: minimal
test_script:
- cmd: >-
    %xunit20%\xunit.console Tests\bin\Release\net472\Tests.dll

    dotnet test "Tests\Tests.csproj" --framework netcoreapp2.0 --configuration Release --no-build --output bin\Release\netcoreapp2.1

artifacts:
- path: nugets\**\*.nupkg