image: Visual Studio 2019 Preview
build_script:
- ps: >-
    dotnet build src --configuration Release

    dotnet test src --configuration Release --no-build --no-restore --filter Category!=Integration
test: off
artifacts:
- path: nugets\*.nupkg